### ISSUE TITLE
Strings get mangled when retrieved

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/rusty_btreec#2]
Using either `String` or `CString` type causes mangling of returned values. I was expecting that for `String` but having `CString` types mangled is unexpected. Need to investigate what's causing the problem

Test case:
https://github.com/bartlomieju/rusty_btreec/blob/593814b35bda5ca7734aaa4513cdbfe01e030c98/src/lib.rs#L230-L239

Using `String`:
```
---- ascend_descend stdout ----
a User {
    first: "Roger",
    last: "Craig",
    age: 68,
} b User {
    first: "Crai",
    last: "Rogery",
    age: 44,
} cmp Less
a User {
    first: "Jane",
    last: "Murphy",
    age: 47,
} b User {
    first: "Murph",
    last: "Janeg",
    age: 68,
} cmp Greater
a User {
    first: "Jane",
    last: "Murphy",
    age: 47,
} b User {
    first: "Jane",
    last: "Murphy",
    age: 44,
} cmp Equal
```

Using `CString`:
```
---- ascend_descend stdout ----
a User {
    first: "Roger",
    last: "Craig",
    age: 68,
} b User {
    first: "Crai",
    last: "Roger\x00",
    age: 44,
} cmp Less
a User {
    first: "Jane",
    last: "Murphy",
    age: 47,
} b User {
    first: "Murph",
    last: "Jane\x00",
    age: 68,
} cmp Greater
a User {
    first: "Jane",
    last: "Murphy",
    age: 47,
} b User {
    first: "Jane",
    last: "Murphy",
    age: 44,
} cmp Equal
```

**Comment by bartlomieju** [comment]
@tidwall I noticed that `btree.c` uses following pragmas:
```
#ifdef __clang__
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wvla"
#endif
```
The first one is suspicious to me and might be a cause for the mangled strings, does the lib depend on some kind of UB as an optimization that the pragma is needed? 

EDIT: Nvm, looks like an overflow caused by my mistake in pointer casting.

**Comment by tidwall** [comment]
Ok, but just in case, I pushed an update to the btree.c that explicitly pads all structs, replaced the one instance of the VLA with a preallocation, and removed pragmas.

**Comment by bartlomieju** [comment]
Long story short - what I was doing was not correct - we can't really store structs that have `String` (or any other fat pointers) in fields. Once they are copied over by C code the Rust will deallocate the structs and the pointers might be invalid.
Once I changed definitions to use `&'static str` everything works nicely and data is properly retrieved from the `btree`.

So it seems we might be restricted to using only primitive types (or the types that are `Copy`). For now I got the `BTreeC::ascend` working, I will later check if I can make the actual types used in `BuntDB`'s `DbItem` work properly.

**Comment by tidwall** [comment]
Is it possible to use `mem::forget` or `mem::ManuallyDrop` before copying to C?

**Comment by bartlomieju** [comment]
> Is it possible to use `mem::forget` or `mem::ManuallyDrop` before copying to C?

I did not think about that, but indeed it seems that calling `mem::forget` after passing the value to `btree_set()` make it work correctly as well (it has to happen after `btree_set()` because `forget()` "moves" the Rust value and it can't be used anymore) 👍  I'm wondering how to approach methods like `btree_delete()` - AFAICT the relevant struct is stored in the "spare" array and it available until the next call to `btree` - so I guess we'd have to copy the data back in Rust to retain the ownership.

**Comment by bartlomieju** [comment]
Gonna close this issue for now. 

Ported all methods required for `buntdb` which should unblock me on the work there.

Still need to fix a few return types and port benchmarks, but that can be addressed along the way.
